# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='mage',
            new_name='image',
        ),
    ]
