# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180514_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='', max_length=200, upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
