# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-20 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180520_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
